/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: fc65e6db0adfb840655702530a44d7c3)
interface __BaseEnv_Env {
	REVIEW_LOGIN_LIMITER: RateLimit;
	COMPILER_LIMITER: RateLimit;
	ASSETS: Fetcher;
	AUTH_MODE: string;
	HOSTED_COMPILER_ENABLED: string;
	PUBLIC_REVIEW_EXPIRES_AT: string;
	PUBLIC_REVIEW_NOT_BEFORE: string;
	REQUIRE_ACCESS_JWT: string;
	REVIEW_AUTH_VERSION: string;
	ACCESS_POLICY_AUD: string;
	ACCESS_TEAM_DOMAIN: string;
	REVIEW_PASSWORD: string;
	REVIEW_SESSION_SECRET: string;
	COMPILER: DurableObjectNamespace<import("./deploy/cloudflare/worker").CompilerContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./deploy/cloudflare/worker");
		durableNamespaces: "CompilerContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
