/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 893faeaf734bc8c9ec9395300bab6355)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	HOSTED_COMPILER_ENABLED: string;
	PUBLIC_REVIEW_EXPIRES_AT: string;
	PUBLIC_REVIEW_NOT_BEFORE: string;
	REQUIRE_ACCESS_JWT: string;
	ACCESS_POLICY_AUD: string;
	ACCESS_TEAM_DOMAIN: string;
	COMPILER: DurableObjectNamespace<import("./deploy/cloudflare/worker").CompilerContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./deploy/cloudflare/worker");
		durableNamespaces: "CompilerContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
